export const propertiesData = [
  {
    id: 1,
    address: " Lowe Fork, United Kingdom",
    postCode: "20095",
    rooms: "5",
    floorArea: "63",
    type: "flat",
  },
  {
    id: 2,
    address: "Tunnel Rowland, United Kingdom",
    postCode: "20095",
    rooms: "5",
    floorArea: "63",
    type: "flat",
  },
  {
    id: 3,
    address: "Fritsch Arizona, United Kingdom",
    postCode: "20095",
    rooms: "5",
    floorArea: "63",
    type: "terraced-house",
  },
  {
    id: 4,
    address: "Fritsch Arizona, United Kingdom",
    postCode: "20095",
    rooms: "5",
    floorArea: "63",
    type: "terraced-house",
  },
  {
    id: 5,
    address: "fritsch Arizona, United Kingdom",
    postCode: "20095",
    rooms: "5",
    floorArea: "63",
    type: "semi-detached",
  },
];
